defaults:
  - bert_config
  - _self_   
  
data:
  batch: 32
  vocab_size: 15
  max_src_len: 10
  num_segments: 2

model:
  saved_model_path: "trained_models/bert.pth"

embedding:
  dim: 8

attention:
  layers: 2
  num_heads: 2
  ffn_multiplier: 4
  activation: gelu

regularization:
  embed_dropout: 0.1
  attn_dropout: 0.1
  ffn_dropout: 0.1

optimizer:
  name: "Adam"
  kwargs:
    lr: 0.001
    weight_decay: 0.0
    betas: [0.9, 0.98]
    eps: 1e-5
