name: CI

on: push

jobs:
  Setup_env:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Poetry
        uses: abatilo/actions-poetry@v3
        with:
          poetry-version: "1.8.3"
          cache: "pip"
          
      - name: Install dependencies
        run: poetry install

  Test:
    runs-on: ubuntu-latest
    name: test
    needs: Setup_env

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"

      - name: Install py packages
        run: pip install -r requirements.txt

      - name: Run tests
        run: poetry run python -m seq2seq.modules.bert 
        
  Train:
    runs-on: ubuntu-latest
    name: test
    needs: Setup_env

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"

      - name: Install py packages
        run: pip install -r requirements.txt
        
      - name: BERT train
        run: poetry run python -m seq2seq.training.train_bert 