name: CI

on: push

jobs:
  job_1:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Poetry
        uses: abatilo/actions-poetry@v3
        with:
          poetry-version: "1.8.3"
          
      - name: Install dependencies
        run: poetry install

      - name: Run tests
        run: poetry run pytest

      - name: BERT train
        run: poetry run python -m seq2seq.training.train_bert 